include:
  - project: 'tpe/testmo-reporter'
    ref: master
    file: '/scenarios/testmo-multiple.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

variables:
  PUBLIC_REPO_URL: git@github.com:ProtonVPN/win-app.git
  SCREENSHOT_PATH: src/bin/TestFailureData/
  TEST_REPORT_PATH: results/
  PROJECT_ID: "1"
  MILESTONE: "Automation"

stages:
  - release
  - bot # comes from translations/generator job
  - build
  - test
  - sign
  - build-installer
  - internal-beta
  - publish-to-slack
  - test-setup
  - ui-test
  - test-upload
  - installation-test
  - test-cleanup
  - mirror

sign:
  stage: sign
  tags:
    - windows
  script:
    - echo "Signing files..."
    - python ci\main.py sign
  artifacts:
    expire_in: 1 day
    paths:
      - src/bin/
  only:
    - master
    - /^release.*$/
    - develop

build-release:
  stage: build
  tags:
    - windows
  script:
    - echo "Restoring NuGet Packages..."
    - 'c:\nuget\nuget.exe restore ProtonVpn.sln'
    - MSBuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "src\\ProtonVPN.MarkupValidator\\ProtonVPN.MarkupValidator.csproj"
    - echo "Building native dependencies..."
    - 'c:\nuget\nuget.exe restore ProtonVPN.InstallActions.sln'
    - cmd.exe /c BuildDependencies.bat
    - python ci\main.py lint-languages
    - python ci\main.py add-commit-hash $env:CI_COMMIT_SHORT_SHA
    - python ci\main.py defaultConfig
    - echo "Building release..."
    - MSBuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "ProtonVpn.sln"
  artifacts:
    expire_in: 1 day
    paths:
      - src/bin/
  only:
    - master
    - /^release.*$/
  variables:
    GIT_SUBMODULE_STRATEGY: normal

build-debug:
  stage: build
  tags:
    - windows
  script:
    - echo "Restoring NuGet Packages..."
    - 'c:\nuget\nuget.exe restore ProtonVpn.sln'
    - MSBuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "src\\ProtonVPN.MarkupValidator\\ProtonVPN.MarkupValidator.csproj"
    - echo "Building native dependencies..."
    - 'c:\nuget\nuget.exe restore ProtonVPN.InstallActions.sln'
    - cmd.exe /c BuildDependencies.bat
    - echo "Downloading translations from crowdin..."
    - python ci\main.py lint-languages
    - python ci\main.py add-commit-hash $env:CI_COMMIT_SHORT_SHA
    - python ci\main.py defaultConfig
    - echo "Building debug..."
    - MSBuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Debug /verbosity:quiet "ProtonVpn.sln"
  artifacts:
    expire_in: 1 day
    paths:
      - src/bin/
  except:
    - master
    - /^release.*$/
  variables:
    GIT_SUBMODULE_STRATEGY: normal

tests:
  stage: test
  tags:
    - windows
  script:
    - echo "Running tests..."
    - 'c:\nuget\nuget.exe restore ProtonVpn.sln'
    - MSBuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Debug /verbosity:quiet "ProtonVpn.sln"
    - coverlet src\bin --target "vstest.console.exe" --targetargs "src/bin/ProtonVPN*Tests*.dll /TestCaseFilter:TestCategory!=UI&TestCategory!=Connection /Platform:x64" --format cobertura --output .\coverage-reports --exclude "[*.Tests*]*" --exclude "[ProtonVPN.MarkupValidator]*" --exclude "[TestTools*]*" --exclude "[TapInstaller]*" --exclude "[*.Installers]*"
    - powershell -Command "(gc coverage-reports.cobertura.xml) -replace '\\', '/' | Out-File -encoding UTF8 cobertura.xml"
    - ReportGenerator.exe "-reports:cobertura.xml" "-targetdir:.\code-coverage-report-html"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/Total.*?([0-9]{1,3}.[0-9]{1,3})%/'

build-installer-for-release:
  stage: build-installer
  tags:
    - windows
  script:
    - python ci\main.py tap-installer
    - python ci\main.py tun-installer
    - python ci\main.py update-gh-list
    - python ci\main.py app-installer $env:CI_COMMIT_SHORT_SHA
  artifacts:
    paths:
      - Setup/ProtonVPN-SetupFiles/
      - Setup/ProtonVPNTun-SetupFiles/
      - Setup/ProtonVPNTap-SetupFiles/
    expire_in: 4 weeks
  only:
    - master
    - /^release.*$/

prepare-internal-beta-release:
  stage: internal-beta
  tags:
    - windows
  when: manual
  script:
    - python -m pip install -r ci\python-libs.txt
    - python ci\prepare-internal-beta.py
  only:
    - /^release.*$/

build-installer-for-debug:
  stage: build-installer
  tags:
    - windows
  script:
    - python ci\main.py tap-installer
    - python ci\main.py tun-installer
    - python ci\main.py update-gh-list
    - python ci\main.py app-installer $env:CI_COMMIT_SHORT_SHA
  artifacts:
    paths:
      - Setup/ProtonVPN-SetupFiles/
    expire_in: 4 weeks
  except:
    - master
    - /^release.*$/

testmo-setup:
  allow_failure: true
  stage: test-setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "release/9.9.9" || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ "/debug/"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ "/release/"
      variables:
        SOURCE: "Release"
    - when: always
  variables:
    SOURCE: "Automation"
    NAME: "$CI_JOB_STARTED_AT UTC"
    TAGS: "$CI_COMMIT_REF_SLUG"

ui-test:
  stage: ui-test
  tags:
    - ui_tests
  script:
    - powershell -File ci\uninstall-app.ps1
    - powershell -File ci\install-the-app.ps1
    - VSTest.Console.exe src\bin\ProtonVPN.UI.Tests.dll /TestCaseFilter:"Category=UI" /Settings:ci/TestRun/test-run-settings.xml
    - powershell -File ci\uninstall-app.ps1
  after_script:
    - powershell.exe ./ci/TestRun/converter-nunit-junit.ps1
  except:
    - /^debug.*$/
    - release/9.9.9
    - master
  artifacts:
    when: always
    name: "result-ui"
    paths:
      - $SCREENSHOT_PATH
      - "results/*"
    expire_in: 1 weeks
  
connection-tests:
  stage: ui-test
  tags:
    - connection_tests
  script:
    - powershell -File ci\uninstall-app.ps1
    - powershell -File ci\install-the-app.ps1
    - VSTest.Console.exe src\bin\ProtonVPN.UI.Tests.dll /TestCaseFilter:"Category=Connection" /Settings:ci/TestRun/test-run-settings.xml
    - powershell -File ci\uninstall-app.ps1
  after_script:
    - powershell.exe ./ci/TestRun/converter-nunit-junit.ps1
  except:
    - /^debug.*$/
    - release/9.9.9
    - master
  artifacts:
    when: always
    name: "result-connection"
    paths:
      - $SCREENSHOT_PATH
      - "results/*"
    expire_in: 1 weeks
    
testmo-upload:
  allow_failure: true
  stage: test-upload
  variables:
    RESULT_FOLDER: "results/*.xml"

win-11-tests:
  stage: ui-test
  when: manual
  tags:
    - win11
  script:
    - powershell -File ci\uninstall-app.ps1
    - powershell -File ci\install-the-app.ps1
    - VSTest.Console.exe src\bin\ProtonVPN.UI.Tests.dll /TestCaseFilter:"Category=Smoke"
  except:
    - /^debug.*$/
    - release/9.9.9
    - master
  artifacts:
    when: on_failure
    paths:
      - $SCREENSHOT_PATH
    expire_in: 2 weeks

mirror:
  stage: mirror
  tags:
    - windows
  only:
    refs:
      - tags
      - master
  script:
    - python ci\main.py prepare-ssh $env:SSH_PRIVATE_KEY
    - ssh-keyscan -t rsa github.com | Set-Content "$env:userprofile\.ssh\known_hosts"
    - git clone "$CI_REPOSITORY_URL" --branch master _APP_CLONE;
    - cd _APP_CLONE
    - git remote add public $PUBLIC_REPO_URL
    - git push public master
    - git push public "$(git describe --abbrev=0)"

i18n-sync-crowdin:
  when: manual
  variables:
    I18N_SYNC_CROWDIN_PROJECT: 'windows-vpn'
  extends: .i18n-sync-crowdin-common

i18n-manual-sync-crowdin:
  when: manual
  only:
    - branches
  variables:
    I18N_SYNC_CROWDIN_PROJECT: 'windows-vpn'
  extends: .i18n-sync-crowdin-common

i18n-commit-translations:
  extends: .i18n-commit-locales-shared
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: 'windows-vpn'
  before_script:
    - git config --global core.autocrlf false

create-release:
  image: debian:stable-slim
  stage: release
  when: manual
  only:
    refs:
      - develop
      - develop-v2
  script:
    - apt-get update && apt-get install -y python3 python3-pip git
    - python3 ci/release.py

send-slack-notification:
  tags:
    - windows
  only:
    refs:
      - develop
  stage: publish-to-slack
  script:
    - python -m pip install -r ci\python-libs.txt
    - python ci\main.py send-slack-notification